function train_net_1layer_filter()
    load('P.mat', 'P');
    load('net_filter.mat', 'net_filter');
    P = net_filter(P);
    T = repmat(eye(10), 1, 50);
    W1=-1 + 2.*rand(10,256);
    b1=-1 + 2.*rand(10,1);
    net_1layer_filter = network(1,1,1,1,0,1);
    net_1layer_filter.layers{1}.size = 10;
    net_1layer_filter.b{1} = b1;
    net_1layer_filter.inputs{1}.size = 256;
    net_1layer_filter.IW{1} = W1;
    net_1layer_filter.layers{1}.transferFcn = 'logsig';
    net_1layer_filter.outputs{1}.processFcns = {'mapminmax'};
    net_1layer_filter.outputs{1}.ProcessParams{1}.ymin = 0;
    net_1layer_filter.outputs{1}.ProcessParams{1}.ymax = 1;
    net_1layer_filter.performParam.lr = 0.5;
    net_1layer_filter.performFcn = 'sse';
    net_1layer_filter.trainFcn='trainscg';
    net_1layer_filter.trainParam.epochs = 1000;
    net_1layer_filter.trainParam.show = 35;
    net_1layer_filter.trainParam.goal = 1e-6;
    % net_2layer_softmax_extra.trainParam.min_grad = 1e-6;
    % net_2layer_softmax_extra.trainParam.max_fail = 10;
    [trainInd,valInd,testInd] = divideind(500,1:425,426:500,[]);
    net_1layer_filter.divideFcn = 'divideind';
    net_1layer_filter.divideParam.trainInd = trainInd;
    net_1layer_filter.divideParam.valInd = valInd;
    net_1layer_filter.divideParam.testInd = testInd;
    net_1layer_filter = train(net_1layer_filter,P,T);
    save net_1layer_filter.mat net_1layer_filter;
end